### ISSUE TITLE
Country Code Translation

### ISSUE THREAD

**Issue by Spectrum5Ghz** [chrissanders/FlowBAT#12]
Good Afternoon,

We are requesting that the Country Codes be translated to Country Names to make it easier to identify source and destination countries. Also, ASN number population would be cool.

**Comment by tdesrochers** [comment]
If I'm not mistaken the country codes are taken directly from silk and not from anything Chris and his crew have developed.  

So I don't think that changing them in flowbat is the solution. Look into how to display changes in country code in sil . I'm not sure if it is even possible

**Comment by automayt** [comment]
Due to the finite amount of values, I am pretty sure that I can do a translation in the background similar to the way I worked out the protocol translation and port translation values. Can't make any promises, but it is close to a promise. Going to try to work this into the next release.

**Comment by automayt** [comment]
#11 fixes this issue. Will close upon merge.

**Comment by chrissanders** [comment]
Should be fixed now in v.1.3
