### ISSUE TITLE
Error Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password)

### ISSUE THREAD

**Issue by dzungbkk51** [chrissanders/FlowBAT#22]
Dear
I setting up flowbat for my system with remote sensor. So when i type querry and see a Warning "Oh snap!"
Permission denied, please try again.

Permission denied, please try again.

Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password)

I can't see chart, pie v...v 
So, what can i do fix this Error? My account can ssh to sensor and have permission sudoer
I sent a image shooted[
![screenshot from 2016-09-15 15-42-33](https://cloud.githubusercontent.com/assets/22212295/18543692/4d82bfc0-7b5b-11e6-93e4-076f9e8be16d.png)
](url)

**Comment by automayt** [comment]
This was resolved as an issue with SSH configuration.
