### ISSUE TITLE
Make warning for sudo installs

### ISSUE THREAD

**Issue by automayt** [chrissanders/FlowBAT#26]
sudo installs might result in a non-functioning install from the install scripts. Those installs require significant manual efforts to finish installing. This addition will add a warning in the beginning, or require an "option" to proceed with a sudo install.

**Comment by eazzhao** [comment]
after i install,i can't see rfwlowpack pid and yaf pid 
how i need do ,i use CentOS 7

**Comment by eazzhao** [comment]
the warning:
It appears that you do not have an internet connection! This installation will fail.
