### ISSUE TITLE
Set custom tmp directory for transient .rwf files

### ISSUE THREAD

**Issue by eacheach** [chrissanders/FlowBAT#6]
When running queries, /tmp appears to be used to store .rwf file output from rwfilter which is later processed but another tool like rwcut, rwstats, etc.  When querying a large about of data, these working files can be very large.  Our /tmp directory is on a rather small file system and can become full when running large queries.  Our data directory for SiLK however is relatively large.  We'd like to either have a configurable option to set the directory where the temporary .rwf files are stored of have them default to the SiLK data directory.

**Comment by eacheach** [comment]
Actually, after working through this a little more, having the temp directory being inside the flowbat installation directory may make more sense since the SiLK data may be remote.

**Comment by chrissanders** [comment]
This issue has been resolved in FlowBAT 1.2.0. The temp directory used to store these files is now user configurable.Thanks!
